# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JamoShGatia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JamoShGatia
pod 'Adjust'
  
pod 'FBSDKCoreKit'
end
